name: CI_RO

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

jobs:
  #bellow is a job name, is defined by user.
  build_image:
    name: upload image to Dockerhub.
    #defines the type of operating system on which the job will run.
    runs-on: ubuntu-latest

    # this a sequence of tasks that will be executed
    steps:
      #every step must define a `uses` or `run` key
      #Below is the name of one of the task sequences.
      - name: Pull repository into Virtual Machine
        #uses actions/checkout for pull repository into the Virtual Machine, in this case ubuntu-lastest.
        uses: actions/checkout@master

      - uses: NRO04/docker-build-push-action@v2
        # This action will build and push the image to dokcerhub.

        # Bellow are arguments for the above action.
        with:
          tag: v1
          # uses the name repository of github for dockerhubs's name repository.
          docker-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker-password: ${{ secrets.DOCKER_HUB_PASSWORD }}
